// <auto-generated />
using System;
using JosephFlores_Examen1P.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JosephFlores_Examen1P.Migrations
{
    [DbContext(typeof(JosephFlores_Examen1PContext))]
    [Migration("20241028153934_Inicio6")]
    partial class Inicio6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JosephFlores_Examen1P.Models.JF_Proteina", b =>
                {
                    b.Property<int>("JFProteinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JFProteinaId"));

                    b.Property<DateTime?>("JFDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("JFName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("JFPrecio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("JFWheyProtein")
                        .HasColumnType("bit");

                    b.HasKey("JFProteinaId");

                    b.ToTable("JF_Proteina");
                });

            modelBuilder.Entity("JosephFlores_Examen1P.Models.Promo", b =>
                {
                    b.Property<int>("PromoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromoId"));

                    b.Property<DateTime?>("Date")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int>("ProteinaID")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PromoId");

                    b.HasIndex("ProteinaID");

                    b.ToTable("Promo");
                });

            modelBuilder.Entity("JosephFlores_Examen1P.Models.Promo", b =>
                {
                    b.HasOne("JosephFlores_Examen1P.Models.JF_Proteina", "Proteina")
                        .WithMany("JFProteins")
                        .HasForeignKey("ProteinaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proteina");
                });

            modelBuilder.Entity("JosephFlores_Examen1P.Models.JF_Proteina", b =>
                {
                    b.Navigation("JFProteins");
                });
#pragma warning restore 612, 618
        }
    }
}
